language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget https://github.com/erpcya/adempiere/releases/latest/download/Adempiere_393LTS.tar.gz  -c -O Adempiere.tar.gz
  - tar -xzf Adempiere.tar.gz
  - mv Adempiere/lib/*.jar dependences/
  - wget http://services.gradle.org/distributions/gradle-6.1.1-bin.zip
  - unzip -qq gradle-5.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  
jobs:
  include:
    - stage: Compilation
      script: gradle build
    - stage: Compilation
      script: gradlew createRelease
deploy:
  provider: releases
  token: $GITHUB_TOKEN_KEY
  skip_cleanup: true
  file: 
    - "$TRAVIS_BUILD_DIR/build/release/adempiere-gRPC-Server.zip"
    - "$TRAVIS_BUILD_DIR/build/release/adempiere-gRPC-Server.tar"
    - "$TRAVIS_BUILD_DIR/build/release/adempiere-gRPC-Server.tar.MD5"
    - "$TRAVIS_BUILD_DIR/build/release/adempiere-gRPC-Server.zip.MD5"
  on:
    tags: true
