language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget https://github.com/erpcya/adempiere/releases/latest/download/Adempiere_393LTS.tar.gz  -c -O Adempiere.tar.gz
  - tar -xzf Adempiere.tar.gz
  - mv Adempiere/lib/*.jar dependences/
  
jobs:
  include:
    - stage: Compilation
      script: ./gradlew build
deploy:
  provider: releases
  token: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/build/distributions/adempiere-gRPC-Server.zip"
    - "$TRAVIS_BUILD_DIR/build/distributions/adempiere-gRPC-Server.tar"
  deploy.skip_cleanup: true
  on:
    tags: true