language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget https://github.com/erpcya/adempiere/releases/download/3.9.2-rc-1.4/Adempiere_392LTS.tar.gz  -c -O Adempiere.tar.gz
  - tar -xzf Adempiere.tar.gz
  - mv Adempiere/lib/*.jar dependences/
  
jobs:
  include:
    - stage: Compilation
      script: ./gradlew build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/build/distributions/adempiere-gRPC-Server.zip"
    - "$TRAVIS_BUILD_DIR/build/distributions/adempiere-gRPC-Server.tar"
  skip_cleanup: true
  on:
    tags: true